site_name: "mroske.pro"
repo_name: github/Kajetan7
repo_url: https://github.com/Kajetan7
site_url: https://www.mroske.pro
theme:
  name: dracula
  logo: assets/avatar.jpg
  favicon: assets/favicon.ico
  custom_dir: 'overrides'
extra:
  search: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Kajetan7
      name: GitHub
nav:
  - Who am I?: index.md
  - Experience: sections/experience.md
  - Projects: sections/projects.md
  - Certifications: sections/certifications.md
  - Education: sections/education.md
  - Recommendations: sections/recommendations.md
extra_css:
  - assets/custom.css